version: '3'

services:
  db:
    image: postgis/postgis:13-3.1 # postgres:13
    restart: always
    environment:
      - POSTGRES_DB=rudedb
      - POSTGRES_USER=usertest
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5442:5432"

volumes:
  postgres-data: